/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import view.MainScreen;



public class App {
  

    public static void main(String[] args) {
        
        MainScreen mainscreen = new MainScreen();
        mainscreen.setVisible(true);
        
    }
}
